In [2]:
import pandas as pd

df = pd.read_csv("student.csv")
print(df)

   rollno    name  age    city  marks
0       1    john   23    pune     99
1       2   blake   24  Mumbai     78
2       3   scott   25    pune    100
3       4  Martin   26    pune     87

In [5]:
df.loc[0,"age"]

np.int64(23)

In [3]:
df.loc[0]

rollno       1
name      john
age         23
city      pune
marks       99
Name: 0, dtype: object

In [6]:
df.loc[[0,1]]

   rollno   name  age    city  marks
0       1   john   23    pune     99
1       2  blake   24  Mumbai     78

In [7]:
df.loc[0:3]

   rollno    name  age    city  marks
0       1    john   23    pune     99
1       2   blake   24  Mumbai     78
2       3   scott   25    pune    100
3       4  Martin   26    pune     87

In [8]:
df.loc[df["age"]>24]

   rollno    name  age  city  marks
2       3   scott   25  pune    100
3       4  Martin   26  pune     87

In [9]:
df.iloc[0]

rollno       1
name      john
age         23
city      pune
marks       99
Name: 0, dtype: object

In [11]:
df.iloc[0:3]

   rollno   name  age    city  marks
0       1   john   23    pune     99
1       2  blake   24  Mumbai     78
2       3  scott   25    pune    100

In [12]:
df.iloc[0:3,0:2]

   rollno   name
0       1   john
1       2  blake
2       3  scott

In [13]:
df.iloc[:,0:3]

   rollno    name  age
0       1    john   23
1       2   blake   24
2       3   scott   25
3       4  Martin   26

In [14]:
bankaccount ={
    "cust_id":[1122,2345,6677,8843,8899],
    "cust_name":["John","Martin","Scott","Joe","Harry"],
    "balance":[56000,78000,99000,23456,48976],
    "acct_type":["saving","current","saving","current","saving"],
    "city":["Pune","Mumbai","Nashik","Pune","Nashik"]

}
df = pd.DataFrame(bankaccount)
df

   cust_id cust_name  balance acct_type    city
0     1122      John    56000    saving    Pune
1     2345    Martin    78000   current  Mumbai
2     6677     Scott    99000    saving  Nashik
3     8843       Joe    23456   current    Pune
4     8899     Harry    48976    saving  Nashik

In [15]:
df["roi"] = df["balance"]*0.5
df

   cust_id cust_name  balance acct_type    city      roi
0     1122      John    56000    saving    Pune  28000.0
1     2345    Martin    78000   current  Mumbai  39000.0
2     6677     Scott    99000    saving  Nashik  49500.0
3     8843       Joe    23456   current    Pune  11728.0
4     8899     Harry    48976    saving  Nashik  24488.0

In [16]:
print(df["balance"].mean())
print(df["balance"].max())
print(df["balance"].sum())
print(df["balance"].min())

61086.4
99000
305432
23456

In [18]:
print(df.groupby("acct_type")["balance"].mean())
# print(df.groupby("acct_type")["balance"].sum())
# print(df.groupby("acct_type")["balance"].max())
# print(df.groupby("acct_type")["balance"].min())
# print(df.groupby("acct_type")["balance"].count())
# print(df.groupby("city")["balance"].sum())

acct_type
current    50728.0
saving     67992.0
Name: balance, dtype: float64

In [19]:
print(df.groupby("city")["balance"].sum())

city
Mumbai     78000
Nashik    147976
Pune       79456
Name: balance, dtype: int64

In [20]:
print(df[df["city"]=="Pune"]["balance"].sum())
print(df.groupby("city")["balance"].sum().loc["Pune"])

79456
79456

In [21]:
print(df.groupby("acct_type")["balance"].sum().loc["saving"])

203976

In [22]:
print(df.groupby("acct_type")["balance"].agg(['min','max','count']))

             min    max  count
acct_type
current    23456  78000      2
saving     48976  99000      3

In [23]:
df['acct_type'].value_counts()

acct_type
saving     3
current    2
Name: count, dtype: int64

In [24]:
def calculate_roi(x):
    if x > 50000:  
        return 2.5
    else:
        return 2.6
    
df["roi"] =df["balance"].map(calculate_roi)
df["roi"] =df["balance"].apply(calculate_roi)
df["roi"] = df["balance"].apply(lambda x: 2.5 if x>50000 else 2.6)

In [25]:
df

   cust_id cust_name  balance acct_type    city  roi
0     1122      John    56000    saving    Pune  2.5
1     2345    Martin    78000   current  Mumbai  2.5
2     6677     Scott    99000    saving  Nashik  2.5
3     8843       Joe    23456   current    Pune  2.6
4     8899     Harry    48976    saving  Nashik  2.6

In [ ]:
df.drop("roi",axis=1,inplace=True) # delete roi column

In [ ]:
df.drop(1,inplace=True) # delete single row
# df.drop([0,2,3],inplace=True) # delete multiple rows

In [ ]:
# Create a dictionary

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("students.csv", index=False)

print("CSV file created successfully!")

In [1]:
print("hello")

hello

In [ ]:
# Create a dictionary

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "London", "Paris"]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("students.csv", index=False)

print("CSV file created successfully!")