In [2]:
import pandas as pd

bankaccount ={
    "cust_id":[1122,2345,6677,8843,8899,1122],
    "cust_name":["John","Martin","Scott","Joe","Harry","John"],
    "balance":[56000,78000,99000,23456,48976,56000],
    "acct_type":["saving","current","saving","current","saving","saving"],
    "city":["Pune","Mumbai","Nashik","Pune","Nashik","Pune"]

} 

data = pd.DataFrame(bankaccount)
print(data)

   cust_id cust_name  balance acct_type    city
0     1122      John    56000    saving    Pune
1     2345    Martin    78000   current  Mumbai
2     6677     Scott    99000    saving  Nashik
3     8843       Joe    23456   current    Pune
4     8899     Harry    48976    saving  Nashik
5     1122      John    56000    saving    Pune

In [ ]:
# only Aggregate Function
print("Max Balance :-",data["balance"].max())
print("Min Balance :-",data["balance"].min())
print("Sum of Balance :-",data["balance"].sum())
print("Count :-",data["balance"].count())
print("Average :-",data["balance"].mean())

In [11]:
data.groupby("acct_type").count()
# data.groupby("acct_type")["balance"].count()

           cust_id  cust_name  balance  city
acct_type
current          2          2        2     2
saving           4          4        4     4

In [ ]:
# print average  of each account type-- saving current
data.groupby("acct_type")["balance"].mean()

acct_type
current    50728.0
saving     64994.0
Name: balance, dtype: float64

In [ ]:
# Multiple Aggregation 

data.groupby("acct_type")["balance"].agg(['sum','max','min'])

              sum    max    min
acct_type
current    101456  78000  23456
saving     259976  99000  48976

In [ ]:
# print higehest balance of "Pune" city 

# result = data.groupby("city")["balance"].max()
# print(result['Pune'])

data.groupby("city")["balance"].max()[["Pune"]]

city
Pune    56000
Name: balance, dtype: int64

In [ ]:
# print higehst balance of each city with employee name

result = data.groupby("city").max()
print(result[['cust_name','balance']])

       cust_name  balance
city
Mumbai    Martin    78000
Nashik     Scott    99000
Pune        John    56000

In [ ]:
data.groupby("city").max()[["Pune"]]

print(r[['cust_name','balance']])

In [ ]:
create dataframe -- Department 
Deptid  deptname   age   role   salary  --- add 5 to 6 records

1. show "It" department max salary 
2. show max ,min and avg salary of each role
3. print number of employees in "HR" department
4. print sum of salary of each deptartment with displaying name and role